version: '3'
services:
  php-fpm:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./docker/php
    environment:
      - "PSQL_PORT=5432"
      - "PSQL_HOST=postgres"
    volumes:
      - ./:/var/www
      - composer:/root/.composer/cache
      - ~/.composer/auth.json:/root/.composer/auth.json
    depends_on:
      - postgres
      - rabbitmq

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "443:443"

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      - "POSTGRES_DB=upgrade"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"

  rabbitmq:
    image: bitnami/rabbitmq:latest
    hostname: docker-rabbitmq
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq-api:/var/lib/rabbitmq
    environment:
      - "RABBITMQ_USERNAME=rabbit"
      - "RABBITMQ_PASSWORD=rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_db:
  composer:
  rabbitmq-api: