version: '3.8'

services:
  php-fpm:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./docker/php
    environment:
      PHP_IDE_CONFIG: "serverName=test.loc"
      PSQL_PORT: "5432"
      PSQL_HOST: "postgres"
    volumes:
      - ./src:/var/www
      - composer:/root/.composer/cache
    depends_on:
      - postgres
      - rabbitmq
      - redis

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./src:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      - "POSTGRES_DB=upgrade"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"

  postgres-test:
    image: postgres:11.2-alpine
    volumes:
      - postgres_db_test:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    environment:
      - "POSTGRES_DB=upgrade_test"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_db:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image: bitnami/rabbitmq:latest
    hostname: docker-rabbitmq
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq-api:/var/lib/rabbitmq
    environment:
      - "RABBITMQ_USERNAME=rabbit"
      - "RABBITMQ_PASSWORD=rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_db:
  postgres_db_test:
  redis_db:
  composer:
  rabbitmq-api: